### ISSUE TITLE
Still asking publisher in 1.1.40

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-generator-code#144]
@joaomoreno Did you publish a wrong version?

https://www.npmjs.com/package/generator-code

The latest one is 1.1.40, but on the commit history I see only 1.1.39.
I'll start making contributions to this package to smoothen the getting started experience. So maybe you can just give me publishing right and I'll fix it.

**Comment by joaomoreno** [comment]
Unfortunately, this is what happened:

- The endgame plan lists this project as one to be published during the endgame. So, since @aeschli is out, that's what I've done.
- Apparently that's the wrong way to do things since @egamma sent this message to me: _FYI: I had to rollback the publishing of the vscode-generator-code module. The change had a dependency on 1.29. We should republish once 1.29 is out._ I believe @egamma published 1.1.40.
- It is possible that @egamma forgot to push the changes to this git repo. So now we have to wait for him to deliver those changes.

@aeschli Please confirm whether this module should only be published right after releasing stable. If so, we should update the endgame template and move that checkbox way down.
