### ISSUE TITLE
An argument is not getting passed to the VS Code extension host VS Code process

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/vscode-generator-code#206]
- VSCode Version: 1.45.0
- OS Version: Windows 10

Steps to Reproduce:

1. Generate a new VS Code extension
2. Go to `.vscode/launch.json` and add `--inspect` to the list of arguments to pass
3. Execute `npm test` to run the extension tests
4. Observe `--inspect` lacking in the command output

This makes sense, because the `test` script invokes `/node_modules/vscode/bin/test` and completely bypasses the VS Code debugger configuration and the `test` script does not seem to read it or pass its own command line arguments along onto the VS Code instance it starts:

```ts
    var args = [
        testsWorkspace,
        '--extensionDevelopmentPath=' + extensionsFolder,
        '--extensionTestsPath=' + testsFolder,
        '--locale=' + locale,
    ];
```

Is there another mechanism by which the control host could be started given extra command line arguments? Bonus points for something that works both with F5 to run and debug extensions test and `npm test`.

Does this issue occur when all extensions are disabled?: Does not apply

**Comment by aeschli** [comment]
Not sure exactly why this ended up in the vscode-generator-code project.

Since a while,`/node_modules/vscode/bin/test` got extracted to a separate node module `vscode-test` (https://github.com/microsoft/vscode-test) and made it more customizable. It also lets you pass in args and if I'm not mistaken that should work with inspect as well.

Can you check if that solves your problem? If not I suggest to file a enhancement request to microsoft/vscode-test. (or I move the issue there)

Using launch configurations also from outside VSCode is currently not possible. https://github.com/microsoft/vscode/issues/10979 is the issue for that.
