### ISSUE TITLE
15 vulnerabilities when installing

### ISSUE THREAD

**Issue by Florian-Schoenherr** [microsoft/vscode-generator-code#318]
![image](https://user-images.githubusercontent.com/65456722/144285117-87b10acc-e649-44f0-adfc-a08b5a8eac63.png)
Am I doing something wrong or is this a problem on your end?

**Comment by aeschli** [comment]
I regularly update to the latest versions and try to squash the vulnerabilities, but it's a never-ending task.
Also `yo` is not very fast at updating.

Currently in `generator-code` there's just one vulnerability report:
![image](https://user-images.githubusercontent.com/6461412/144912076-3e20cf39-2c40-4e91-91f9-b8a89d71e1ac.png)
It's caused by `yosay`.

The rest come from `yo`
