### ISSUE TITLE
"Invalid publisher name" is unhelpful

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode-generator-code#50]
The prompt `What's your publisher name?` is unhelpful at best. What's it asking me? My name? My company's name? I tried typing in my first and last name and it reponded with "Invalid publisher name". Only through tracking down the generator source code did I realise that I wasn't allowed to use a space in the name. I still don't know what the publisher name is for, or why I should care, or why it cares whether or not I use a space. You should make the error message a bit more helpful, and perhaps clarify the prompt, e.g. `Who owns this project? (No spaces, please)`

**Comment by bpasero** [comment]
@axefrog please see https://code.visualstudio.com/docs/tools/vscecli#_publishing-extensions

@joaomoreno if you have ideas how to help users better here

**Comment by axefrog** [comment]
@bpasero yep I got there in the end, though now the publishing/installing system is being [extremely flakey](https://github.com/Microsoft/vscode/issues/12497), but I digress...

**Comment by joaomoreno** [comment]
@bpasero Just print that link right before the `What's your publisher name?` question.

**Comment by capaj** [comment]
@joaomoreno yes! that's the way to resolve this problem.

**Comment by bpasero** [comment]
Available in generator-code 1.1.7.

**Comment by cfjedimaster** [comment]
I think this should be re-opened. I just ran into this myself and the link providing in the output (https://code.visualstudio.com/docs/extensions/publish-extension#_publishing-extensions) isn't necessarily immediately helpful. Form what I can tell, you need to get down to the "Create a publisher" aspect to figure out what is going on. And if I just want to *test* building an extension, isn't this a lot of work todo? I tried entering nothing and it wouldn't let me get past it. 

As an example, I was entering "Raymond Camden", and the issue was that it didn't like the spaces. I could enter an invalid publisher just fine once I realized that. (To be clear, I *have* a publisher account, I'm just thinking about other folks who may not.) Perhaps it could allow a blank entry and use something like "unknown" or "blank" as the value?

**Comment by olsonpm** [comment]
I uninstalled `yo` and `generator-code` as soon as I clicked the link showing the publisher name.  All I wanted to do was create a local custom command which that page said I'd be doing.

**Comment by monsterbrain** [comment]
> Azure DevOps Services

As complicated as it sounds, your reply actually helped me to go through the registration process better than the official doc itself. :)

**Comment by mauriciogracia** [comment]
Publisher name can not have spaces nor special symbols like ".@{}" 

I ended up using -> "publisher": "MGG"
