### ISSUE TITLE
Generator doesn't respond to arrow keys in Windows 10

### ISSUE THREAD

**Issue by xabikos** [Microsoft/vscode-generator-code#8]
I installed the latest version of the generator as pointed in [here][builders]. After doing that the generator launches normally but I can't navigate among the various options with the arrow keys. This happens on Windows 10 environment. I don't know if it's relevant but the same happens to the asp.net yeoman generator. In OS X environment everything works file.

[builders]:https://github.com/Microsoft/vscode-extensionbuilders#update-the-yeoman-generator-to-the-next-version

**Comment by billti** [comment]
The root cause appears to be in Node v4+ (and currently still open).

https://github.com/OmniSharp/generator-aspnet/issues/351
https://github.com/nodejs/node/issues/2996#issuecomment-146240124

Seems like Win10 folks may need to use Node 0.12 for now to use the Yeoman generator for extensions (or use the workaround from @egamma which also worked for me).

**Comment by ilich** [comment]
I am on Node 5.0.0 and Windows 10. It does not work if I run the generator using `yo code` command, but it works if I run `yo` and choose Code  generator there

**Comment by wholroyd** [comment]
I am on Node 5.3.0 with Windows 10. I did have the issue on 4.x until I upgraded, but now no longer have the issue.

**Comment by bpasero** [comment]
Thanks!

**Comment by kia-h** [comment]
if it doesn't wok in Git Bash, try powershell. just run the yo then select your generator

**Comment by bilazik** [comment]
In powershell works great. It don't works from cmd without Admin execution.
 VS code integrated terminal  works fine with Admin opts too.
Thanks guys
