### ISSUE TITLE
launch.json should default version to 0.2.0

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-generator-code#86]

**Comment by aeschli** [comment]
We now recommend to use tasks v2.0.0

**Comment by octref** [comment]
I'm confused. I meant launch.json, namely:

- https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-ts/vscode/launch.json#L3
- https://github.com/Microsoft/vscode-generator-code/blob/master/generators/app/templates/ext-command-js/vscode/launch.json#L3

**Comment by KamasamaK** [comment]
@aeschli This should be reopened as `launch.json` is still 0.1.0 as demonstrated

**Comment by egamma** [comment]
Adding @weinand, can you please review and update the launch.json in yo templates linked in the description.

When I create a launch.json today then the version is `0.2.0`, but it looks like this change was some month ago and since it is a minor version change it cannot breaking.

**Comment by weinand** [comment]
I've updated the 6 launch.json as follows:
- updated version number to "0.2.0" (VS Code never shipped with a "0.1.0" version, so the code generated erroneously used that version. However, this doesn't matter because VS Code is not yet using the version number).
- added our standard IntelliSense comment
- changed variable `workspaceRoot` to `workspaceFolder`
- removed the `"sourceMaps": true` because that's the default anyway
- removed the `"stopOnEntry": false` because that's the default anyway
- changed the formatting of arrays so that it becomes easier and less error prone to add additional items.

**Comment by weinand** [comment]
@aeschli please publish a new version of the generator
